on:
  pull_request:
    types: [opened, synchronize]

env:
  template_name: betrybe/sd-0x-exercise-tryber-calendar

jobs:
  evaluator:
    runs-on: self-hosted
    name: Evaluator
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch Cypress evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/cypress-evaluator-action
          ref: v8
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/cypress-evaluator

      - name: Fetch Store evaluation
        if: ${{ github.repository != env.template_name }}
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v8.0
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Fetch Requirements Evaluation Table
        if: ${{ github.repository == env.template_name }}
        uses: actions/checkout@v2
        with:
          repository: betrybe/requirements-evaluation-table-action
          ref: v1.0
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/requirements-evaluation-table-action

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: "16"

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: "main"

      - name: Run Cypress evaluator
        id: evaluator
        uses: ./.github/actions/cypress-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}
          npm-start: true

      - name: Run Store evaluation
        if: ${{ github.repository != env.template_name }}
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Requirements Evaluation Table
        if: ${{ github.repository == env.template_name }}
        uses: ./.github/actions/requirements-evaluation-table-action
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          pr_number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}